#ifndef KEYSHARP_INPUT_INTERNAL_PROTOCOL_CONTRACT_H
#define KEYSHARP_INPUT_INTERNAL_PROTOCOL_CONTRACT_H

#include <stdint.h>

#define KSI_PROTOCOL_MAJOR 2u
#define KSI_PROTOCOL_MINOR 0u
#define KSI_FRAME_HEADER_SIZE 24u
#define KSI_MAX_MESSAGE_SIZE 65536u
#define KSI_MAX_PAYLOAD_SIZE (KSI_MAX_MESSAGE_SIZE - KSI_FRAME_HEADER_SIZE)
#define KSI_FRAME_MAGIC "KSIP"

typedef enum ksi_frame_flag {
    KSI_FRAME_FLAG_RESPONSE = 0x0001u,
    KSI_FRAME_FLAG_EVENT = 0x0002u,
    KSI_FRAME_FLAG_MORE = 0x0004u,
} ksi_frame_flag;

#define KSI_FRAME_FLAGS_ALL 0x0007u

typedef enum ksi_opcode {
    KSI_OPCODE_HELLO = 0x0001u,
    KSI_OPCODE_AUTHORIZE = 0x0002u,
    KSI_OPCODE_PING = 0x0003u,
    KSI_OPCODE_PERMISSIONS_LIST = 0x0004u,
    KSI_OPCODE_PERMISSIONS_REVOKE = 0x0005u,
    KSI_OPCODE_SESSION_REVOKED = 0x0006u,

    KSI_OPCODE_SUBSCRIBE_HOOK = 0x1000u,
    KSI_OPCODE_UNSUBSCRIBE_HOOK = 0x1001u,
    KSI_OPCODE_HOOK_EVENT = 0x1002u,
    KSI_OPCODE_HOOK_QUARANTINED = 0x1003u,
    KSI_OPCODE_SYNTHESIZE_INPUT = 0x1010u,
    KSI_OPCODE_SET_BLOCK_INPUT = 0x1012u,
    KSI_OPCODE_GET_INDICATOR_STATE = 0x1020u,
    KSI_OPCODE_GET_POINTER_POSITION = 0x1021u,
    KSI_OPCODE_GET_KEY_STATE = 0x1022u,
    KSI_OPCODE_GET_POINTER_BUTTONS = 0x1023u,
    KSI_OPCODE_GET_IDLE_TIME = 0x1024u,
    KSI_OPCODE_GET_MODIFIER_STATE = 0x1025u,
} ksi_opcode;

#define KSI_STATUS_PAYLOAD_SIZE 8u
#define KSI_HELLO_PAYLOAD_SIZE 16u
#define KSI_HELLO_RESULT_PAYLOAD_SIZE 24u
#define KSI_AUTHORIZE_PAYLOAD_SIZE 16u
#define KSI_AUTHORIZE_RESULT_PAYLOAD_SIZE 16u
#define KSI_PERMISSION_HASH_SIZE 32u
#define KSI_PERMISSIONS_LIST_ENTRY_FIXED_SIZE 56u
#define KSI_PERMISSIONS_REVOKE_PAYLOAD_SIZE 48u
#define KSI_SESSION_REVOKED_PAYLOAD_SIZE 8u
#define KSI_HOOK_SUBSCRIPTION_PAYLOAD_SIZE 8u
#define KSI_HOOK_SUBSCRIPTION_RESULT_PAYLOAD_SIZE 16u
#define KSI_HOOK_EVENT_PREFIX_SIZE 8u
#define KSI_KEYBOARD_HOOK_EVENT_SIZE 40u
#define KSI_MOUSE_HOOK_EVENT_SIZE 52u
#define KSI_HOOK_DECISION_PREFIX_SIZE 16u
#define KSI_INPUT_WIRE_SIZE 40u
#define KSI_SYNTHESIZE_PREFIX_SIZE 8u
#define KSI_BLOCK_INPUT_PAYLOAD_SIZE 8u
#define KSI_BLOCK_INPUT_RESULT_PAYLOAD_SIZE 16u
#define KSI_INDICATOR_STATE_PAYLOAD_SIZE 4u
#define KSI_KEY_STATE_PAYLOAD_SIZE 200u
#define KSI_POINTER_POSITION_PAYLOAD_SIZE 28u
#define KSI_POINTER_BUTTONS_PAYLOAD_SIZE 12u
#define KSI_IDLE_TIME_PAYLOAD_SIZE 16u
#define KSI_MODIFIER_STATE_PAYLOAD_SIZE 12u
#define KSI_HOOK_QUARANTINED_PAYLOAD_SIZE 32u

#endif
